- name: vertx-k8-workshop-apb playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    openshift_user: 
    openshift_password: 
    openshift_token:
    openshift_master_url: 
    openshift_user_password:
    project_suffix: "-XX"
    github_account: jbossdemocentral
    github_ref: master
    che_generate_user_count: 10
    infrasvcs_adm_user: adminuser
    infrasvcs_adm_pwd: adminpwd
    infrasvcs_gogs_user_count: 25
    master_url: "kubernetes.default"

  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: ansibleplaybookbundle.asb-modules

  tasks:    
  - name: login as super user with token
    shell: "oc login {{ master_url }} --token={{ openshift_token }} --insecure-skip-tls-verify=true"
    when:
      - openshift_token is defined
      - openshift_token is not none
      - openshift_token|trim() != ""
    tags: always

  - name: login as super user with pwd
    shell: "oc login {{ master_url }} -u {{ openshift_user }} -p {{ openshift_password }} --insecure-skip-tls-verify=true"
    when: >
      openshift_token is not defined or
      openshift_token is none or
      openshift_token|trim() == ""
    tags: always  
          
  - name: extract app route suffix
    block:
      - openshift_v1_route:
          name: dummy
          namespace: "{{ namespace }}"
          state: present
          spec_to_kind: Service
          spec_to_name: dummy
          spec_port_target_port: 8080
        register: dummy_route
      - set_fact:
          apps_hostname_suffix: "{{ dummy_route.route.spec.host|regex_replace('^dummy-' + namespace + '\\.(.*)$', '\\1') }}"
      - openshift_v1_route:
          name: dummy
          namespace: "{{ namespace }}"
          state: absent
    tags: always

  - name: delete project quota
    shell: "oc delete limitrange --all -n {{ namespace }}"
    ignore_errors: true
    tags: always

  # deploy guides
  - import_role:
      name: openshift_workshopper
      allow_duplicates: true
    vars:
      workshopper_name: guides
      project_name: "{{ namespace }}"
      workshopper_content_url_prefix: "https://raw.githubusercontent.com/{{ github_account }}/vertx-kubernetes-workshop/{{ github_ref }}/docs/workshopper-guides"
      workshopper_workshop_urls: "https://raw.githubusercontent.com/{{ github_account }}/vertx-kubernetes-workshop/{{ github_ref }}/docs/workshopper-guides/_workshop-guides-che.yml"
      workshopper_env_vars:
        PROJECT_SUFFIX: "{{ project_suffix }}"
        COOLSTORE_PROJECT: micro-trader-{{ project_suffix }}
        OPENSHIFT_CONSOLE_URL: "{{ openshift_master_url }}"
        ECLIPSE_CHE_URL: http://che-{{ namespace }}.{{ apps_hostname_suffix }}
        GIT_URL: http://gogs-{{ namespace }}.{{ apps_hostname_suffix }}
        NEXUS_URL: http://nexus-{{ namespace }}.{{ apps_hostname_suffix }}
    tags: guides

  # install openjdk imagestream
  - name: get openjdk image stream
    shell: "oc get is java -n openshift"
    register: java_imagestream_result
    ignore_errors: true
    tags: jdk

  - name: install java image stream
    shell: "oc create -n openshift -f https://raw.githubusercontent.com/jboss-container-images/openjdk/develop/templates/image-streams.json"
    when: java_imagestream_result is failed
    tags: jdk
  
  - name: update the java image stream
    shell: "oc replace --force -n openshift -f https://raw.githubusercontent.com/jboss-container-images/openjdk/develop/templates/image-streams.json"
    when: java_imagestream_result is succeeded
    tags: jdk

  # deploy eclipse che
  - import_role:
      name: openshift_eclipse_che
    vars:
      project_name: "{{ namespace }}"
      che_version: "6.8.0"
      multi_user: true
      route_suffix: "{{ apps_hostname_suffix }}"
      keycloak_admin_user: "{{ infrasvcs_adm_user }}"
      keycloak_admin_pwd: "{{ infrasvcs_adm_pwd }}"
      install_java_oc_stack: false
      che_generate_user_password: openshift
      install_custom_stacks_json: |
        [{
          "name": "Java Vert.x",
          "description": "Java JDK Stack on CentOS for Vertx-Workshop",
          "scope": "general",
          "workspaceConfig": {
            "environments": {
              "default": {
                "recipe": {
                  "type": "dockerimage",
                  "content": "quay.io/sshaaf/vertx-workshop-stack"
                },
                "machines": {
                  "dev-machine": {
                    "env": {
                      "MAVEN_OPTS" : "-Xmx512m"
                    },
                    "servers": {
                      "8080/tcp": {
                        "attributes": {},
                        "protocol": "http",
                        "port": "8080"
                      },
                      "8000/tcp": {
                        "attributes": {},
                        "protocol": "http",
                        "port": "8000"
                      },
                      "9000/tcp": {
                        "attributes": {},
                        "protocol": "http",
                        "port": "9000"
                      },
                      "9001/tcp": {
                        "attributes": {},
                        "protocol": "http",
                        "port": "9001"
                      }
                    },
                    "volumes": {},
                    "installers": [
                      "org.eclipse.che.exec",
                      "org.eclipse.che.terminal",
                      "org.eclipse.che.ws-agent"
                    ],
                    "attributes": {
                      "memoryLimitBytes": "2147483648"
                    }
                  }
                }
              }
            },
            "commands": [
              {
                "commandLine": "mvn package -f ${current.project.path}",
                "name": "build",
                "type": "mvn",
                "attributes": {
                  "goal": "Build",
                  "previewUrl": ""
                }
              },
              {
                "commandLine": "mvn clean package -f ${current.project.path}",
                "name": "clean build",
                "type": "mvn",
                "attributes": {
                  "goal": "Build",
                  "previewUrl": ""
                }
              },
              {
                "commandLine": "mvn verify -f ${current.project.path}",
                "name": "test",
                "type": "mvn",
                "attributes": {
                  "goal": "Test",
                  "previewUrl": ""
                }
              },
              {
                "commandLine": "mvn vertx:run -f ${current.project.path}",
                "name": "run vertx",
                "type": "mvn",
                "attributes": {

                  "goal": "Run",
                  "previewUrl": "${server.8080/tcp}"
                }
              },
              {
                "commandLine": "cd ${current.project.path}/ && mvn clean compile && mvn exec:java -Dexec.mainClass=io.vertx.workshop.exercise.Exercise1",
                "name": "run Exercise1",
                "type": "mvn",
                "attributes": {
                  "goal": "Run",
                  "previewUrl": "${server.8080/tcp}"
                }
              },
              {
                "commandLine": "cd ${current.project.path}/ && mvn clean compile && mvn exec:java -Dexec.mainClass=io.vertx.workshop.exercise.Exercise2",
                "name": "run Exercise2",
                "type": "mvn",
                "attributes": {
                  "goal": "Run",
                  "previewUrl": "${server.8080/tcp}"
                }
              },
              {
                "commandLine": "cd ${current.project.path}/ && mvn clean compile && mvn exec:java -Dexec.mainClass=io.vertx.workshop.exercise.Exercise4",
                "name": "run Exercise4",
                "type": "mvn",
                "attributes": {
                  "goal": "Run",
                  "previewUrl": "${server.8080/tcp}"
                }
              },
              {
                "commandLine": "cd ${current.project.path}/ && mvn clean compile && mvn exec:java -Dexec.mainClass=io.vertx.workshop.exercise.Exercise5",
                "name": "run Exercise5",
                "type": "mvn",
                "attributes": {
                  "goal": "Run",
                  "previewUrl": "${server.8080/tcp}"
                }
              },
              {
                "commandLine": "cd ${current.project.path}/ && mvn clean compile && mvn exec:java -Dexec.mainClass=io.vertx.workshop.exercise.Exercise6",
                "name": "run Exercise6",
                "type": "mvn",
                "attributes": {
                  "goal": "Run",
                  "previewUrl": "${server.8080/tcp}"
                }
              },
              {
                "commandLine": "cd ${current.project.path}/ && mvn clean compile && mvn exec:java -Dexec.mainClass=io.vertx.workshop.exercise.microservice.Main",
                "name": "run Microservices.Main",
                "type": "mvn",
                "attributes": {
                  "goal": "Run",
                  "previewUrl": "${server.8080/tcp}"
                }
              },              
              {
                "commandLine": "cd ${current.project.path} && mvn clean compile && mvn fabric8:deploy",
                "name": "fabric8:deploy",
                "type": "mvn",
                "attributes": {
                  "goal": "Deploy",
                  "previewUrl": ""
                }
              }
            ],
            "projects": [],
            "defaultEnv": "default",
            "name": "default",
            "links": []
          },
          "components": [
            {
              "version": "---",
              "name": "CentOS"
            },
            {
              "version": "1.8.0_45",
              "name": "JDK"
            },
            {
              "version": "3.2.2",
              "name": "Maven"
            },
            {
              "version": "2.4",
              "name": "Ansible"
            },
            {
              "version": "3.11",
              "name": "OpenShift CLI"
            }
          ],
          "creator": "ide",
          "tags": [
            "Java",
            "JDK",
            "Maven",
            "CentOS",
            "Git"
          ],
          "id": "java-oc-centos-vertx"
        }]
    tags: eclipse-che
